name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Pull latest code
        working-directory: /home/ubuntu/cicd/actions-runner/_cicd/python-cicd/python-cicd
        run: git pull origin main

      - name: Setup Temp Folder
        run: |
            mkdir /tmp/test/
            cp -r /home/ubuntu/cicd/actions-runner/_cicd/python-cicd/python-cicd/. /tmp/test/. || exit 1
            
      - name: Test Build
        working-directory: /tmp/test/
        run: python3 app.py

      - name: Copy Files To Project Root if Build Success
        run: |
            cp -r /home/ubuntu/actions-runner/_cicd/python-cicd/python-cicd/. /home/ubuntu/cicd/test1/. || exit 1
            python3 app.py

        
      
        
